name: 'Firstproj'
version: '1.0.0'
config-version: 2

profile: 'Firstproj'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
clean-targets:
  - "target"
  - "dbt_packages"

models:
  Firstproj:
    customer_table:
      materialized: table
